name: Publish Production Update

jobs:
  publish_update:
    name: Publish OTA Update to Production
    type: update
    params:
      channel: production
      message: ${{ github.event.head_commit.message }}