name: Publish Production Update

on:
  push:
    branches: ['main']

jobs:
  publish_update:
    name: Publish OTA Update to Production
    type: update
    params:
      channel: production
      message: ${{ github.event.head_commit.message }}